import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.tensorboard.writer import SummaryWriter
from src.losses import knnDivergence, MonotonicityLoss
import logging
import os
from tqdm import tqdm
import math
import warnings

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    ## type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def generate_label_distribution(
    num_points=10000, mean=76, std=22.5, min_value=10, max_value=None
):
    """
    Generate a tensor of points sampled from a normal distribution with specified mean and standard deviation
    while rejecting points outside the optional min and max value constraints.

    Args:
        num_points (int): Number of points to generate
        mean (float): Mean of the distribution
        std (float): Standard deviation of the distribution
        min_value (float, optional): Minimum value of the distribution (inclusive)
        max_value (float, optional): Maximum value of the distribution (inclusive)

    Returns:
        torch.Tensor: Tensor of generated points within the specified range
    """
    points_80 = torch.zeros(num_points)  # Initialize a tensor to store valid points
    points_300 = torch.zeros(num_points//2)  # Initialize a tensor to store valid points
    dist_80 = _no_grad_trunc_normal_(
        points_80, mean=76, std=22.5, a = 10 ,
        b= 170
    )
    dist_300 = _no_grad_trunc_normal_(
        points_300, mean=302, std=25, a=170 ,
        b=400 
    )
    output = torch.cat((dist_80, dist_300), dim=0)
    return output

# def generate_label_distribution(
#     num_points=10000, mean=76, std=22.5, min_value=10, max_value=None
# ):
#     """
#     Generate a tensor of points sampled from a normal distribution with specified mean and standard deviation
#     while rejecting points outside the optional min and max value constraints.

#     Args:
#         num_points (int): Number of points to generate
#         mean (float): Mean of the distribution
#         std (float): Standard deviation of the distribution
#         min_value (float, optional): Minimum value of the distribution (inclusive)
#         max_value (float, optional): Maximum value of the distribution (inclusive)

#     Returns:
#         torch.Tensor: Tensor of generated points within the specified range
#     """
#     points = torch.zeros(num_points)  # Initialize a tensor to store valid points
#     dist = _no_grad_trunc_normal_(
#         points, mean=mean, std=std, a=min_value if min_value is not None else -float('inf'),
#         b=max_value if max_value is not None else float('inf')
#     )
#     return dist

# def generate_label_distribution(
#     num_points=10000, mean=76, std=22.5, min_value=10, max_value=None
# ):
#     """
#     Generate a tensor of points sampled from a normal distribution with specified mean and standard deviation
#     while rejecting points outside the optional min and max value constraints.

#     Args:
#         num_points (int): Number of points to generate
#         mean (float): Mean of the distribution
#         std (float): Standard deviation of the distribution
#         min_value (float, optional): Minimum value of the distribution (inclusive)
#         max_value (float, optional): Maximum value of the distribution (inclusive)

#     Returns:
#         torch.Tensor: Tensor of generated points within the specified range
#     """
#     points = torch.empty(0)  # Initialize an empty tensor to store valid points

#     while points.numel() < num_points:
#         # Generate points from normal distribution
#         generated_points = torch.normal(mean=mean, std=std, size=(num_points,))

#         # Filter points based on the min and max values
#         if min_value is not None:
#             generated_points = generated_points[generated_points >= min_value]
#         if max_value is not None:
#             generated_points = generated_points[generated_points <= max_value]

#         # Add the valid points to the tensor
#         points = torch.cat((points, generated_points))
#     # Return only the first `num_points` points
#     return points[:num_points]

class TrainerSize(nn.Module):
    def __init__(
        self,
        model: nn.Module,
        device: torch.device,
        config: dict,
        experiment_dir: str,
        writer: SummaryWriter = None,
        verbose: bool = True,
    ):
        super(TrainerSize, self).__init__()
        self.model = model
        self.device = device
        self.config = config
        self.experiment_dir = experiment_dir
        self.writer = writer
        self.verbose = verbose
        self.optimizer = optim.Adam(
            model.parameters(), lr=self.config["optimizer"]["parameters"]["lr"]
        )
        self.scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            self.optimizer,
            mode=self.config["scheduler"]["parameters"]["mode"],
            factor=self.config["scheduler"]["parameters"]["factor"],
            patience=self.config["scheduler"]["parameters"]["patience"],
        )
        self.checkpoint_path = os.path.join(experiment_dir, "best_model.pth")

        # Configure logging
        self.logger = logging.getLogger(__name__)
        log_level = logging.DEBUG if verbose else logging.WARNING
        logging.basicConfig(
            level=log_level, format="%(asctime)s - %(levelname)s - %(message)s"
        )
        self.weight_monotonicity = self.config["loss"]["monotonicity"]["weight"]
        self.weight_knn_divergence = self.config["loss"]["knn_divergence"]["weight"]
    def train_epoch(
        self,
        train_dataloader: DataLoader,
        label_points: torch.Tensor,
        k_neighbors: torch.Tensor,
    ):
        """
        Train the model for one epoch.

        Args:
            epoch (int): Current epoch number
            dataloaders (list): List of dataloaders for training
            label_points (list): List of label points for training

        Returns:
            None
        """
        total_knn_loss = 0
        total_monotonicity_loss = 0
        total_loss = 0
        for batch_images, particles_cls in train_dataloader:
            target_distribution = torch.clone(label_points)
            batch_images = batch_images.to(self.device)

            # Zero gradients
            self.optimizer.zero_grad()
            # Forward pass: generate predictions
            batch_predictions = self.model(batch_images)
            # Compute KNN divergence loss
            knn_loss_80 = knnDivergence(
                batch_predictions[particles_cls==0],
                target_distribution[:30000],
                k_neighbors=torch.arange(
            2, len(batch_predictions[particles_cls==0])//2, dtype=torch.int
        ),
                method="absolute",
            )
            knn_loss_300 = knnDivergence(
                batch_predictions[particles_cls==1],
                target_distribution[30000:],
                k_neighbors=torch.arange(
            2, len(batch_predictions[particles_cls==1])//2, dtype=torch.int),
                method="absolute",
            )
            knn_loss= knn_loss_80 + knn_loss_300
            # Compute monotonicity loss
            monotonicity_loss = MonotonicityLoss(
                batch_predictions, batch_images, increasing=True
            )
            # Combine losses
            loss = self.weight_knn_divergence*knn_loss + self.weight_monotonicity*monotonicity_loss
            # Backward pass and optimize
            loss.backward()
            self.optimizer.step()

            total_loss += loss.item()
            total_knn_loss += knn_loss.item()
            total_monotonicity_loss += monotonicity_loss.item()

        # Calculate average loss for the epoch
        avg_loss = total_loss / len(train_dataloader)
        avg_knn_loss = total_knn_loss / len(train_dataloader)
        avg_monotonicity_loss = total_monotonicity_loss / len(train_dataloader)
        return avg_loss, avg_knn_loss, avg_monotonicity_loss

    def train(self, train_dataloader: DataLoader, num_epochs: int):
        """
        Train the model for a specified number of epochs.

        Args:
            train_dataloader (DataLoader): Dataloader for training
            num_epochs (int): Number of epochs to train

        Returns:
            None
        """
        # Early stopping parameters
        best_loss = float("inf")
        no_improve = 0
        loss_log = []
        k_neighbors = torch.arange(
            2, self.config["target_distribution"]["k"], dtype=torch.int
        )
        # Training loop
        for epoch in tqdm(
            range(num_epochs),
            disable=not self.logger.isEnabledFor(logging.DEBUG),
        ):
            if epoch % self.config["target_distribution"]["cycle"] == 0:
                # Generate new label points every 5 epochs
                label_points = generate_label_distribution(
                    num_points=self.config["target_distribution"]["num_points"],
                    mean=self.config["target_distribution"]["mean"],
                    std=self.config["target_distribution"]["std"],
                    min_value=self.config["target_distribution"]["min_value"],
                    max_value=self.config["target_distribution"]["max_value"],
                ).to(self.device)
            self.model.train()
            avg_loss, avg_knn_loss, avg_monotonicity_loss  = self.train_epoch(
                train_dataloader, label_points, k_neighbors
            )
            loss_log.append(avg_loss)
            current_lr = self.optimizer.param_groups[0]["lr"]
            # Learning rate scheduling
            self.scheduler.step(avg_loss)

            # Log the loss
            self.logger.info(
                f"Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}, LR: {current_lr:.2e}"
            )
            self.logger.info(
                f"Epoch [{epoch+1}/{num_epochs}], KNN Loss: {avg_knn_loss:.4f}, Monotonicity Loss: {avg_monotonicity_loss:.4f}"
            )
            if self.writer:
                self.writer.add_scalar("Loss/train", avg_loss, epoch)

            # Early stopping check
            if avg_loss < best_loss:
                best_loss = avg_loss
                torch.save(
                    {
                        "epoch": epoch,
                        "model_state_dict": self.model.state_dict(),
                        "optimizer_state_dict": self.optimizer.state_dict(),
                        "loss": best_loss,
                    },
                    self.checkpoint_path,
                )
                no_improve = 0
            else:
                no_improve += 1

            if (
                no_improve >= self.config["early_stopping"]["patience"]
                and self.config["early_stopping"]["enabled"]
            ):
                self.logger.info(f"Early stopping at epoch {epoch+1}")
                break

        return loss_log
