seed: 0
data:
  image_size: 256
  z_chunk_size : 201  # Number of chunks to divide the z-stack into for averaging for cellvit use 12 for eg
  num_z_slices: 201 # Number of z slices to use, can be an integer or "all"
  fluo_masks_indices: [0,1] # classes used for training
  seg_method: "comdet"
  data_type: "Brightfield" # Brightfield/Laser
  normalize: "zscore" # Options: zscore, minmax, none
  multi_class: False
  dataset_folder_path: "/scratch/narjis/iscat_data/"

  train_dataset:
    num_workers: 2
    apply_augmentation: true
    normalize: ${data.normalize} # Do not change
    classes: ${data.fluo_masks_indices} # Do not change
    multi_class: ${data.multi_class}  # Do not change
  valid_dataset:
    num_workers: 2
    apply_augmentation: false
    normalize: ${data.normalize}  # Do not change
    classes: ${data.fluo_masks_indices} # Do not change
    multi_class: ${data.multi_class}  # Do not change
training:
  batch_size: 32 # batch size should be lower for cellvit for eg 10
  num_epochs: 400
  train_split_size: 0.7
  loss:
    loss_type: "tversky" # Options: crossentropy, dice, dicece, tversky
    parameters:
      alpha: 0.4
      beta: 0.6
      gamma: 1.0
      lambda_ce: 0.1
      lambda_dice: 1.0
  class_weights:
    use: True
    calculation_method: "from_masks"
  optimizer:
    type: "AdamW"
    parameters:
      lr: 1e-4 #1e-4
      weight_decay: 1e-4
      betas: [0.9, 0.999]
  scheduler:
    type: "ReduceLROnPlateau"
    parameters:
      mode: "min"
      factor: 0.1
      patience: 8
  early_stopping:
    enabled: true
    patience: 20
testing:

model:
  type: "U_Net" #AttU_Net #R2AttU_Net #U_Net #R2U_Net #CellViT
  unet:
    init_features: 64
  cellvit:
    patch_size: 8
    embed_dim: 384
    depth: 12
    num_heads: 6
    extract_layers: [3, 6, 9, 12]
logging:
  tensorboard:
    log_dir: "experiments/runs/segmentation/commercial_beads"

