seed: 0
data:
  classes: [0,1]  # Classes to include in training
  mean: null  # If null, will be computed from dataset # mean classes 0&1 7541.1983
  std: null   # If null, will be computed from dataset # std classes 0&1 1316.1215
  padding: false
  # dataset_path: "/data_ssd2/iscat_data/brightfield_particles_y.hdf5" "/nfshome/narjis/Downloads/brightfield_particles.hdf5"
  dataset_path: "/home/zakarianarjis/Downloads/particles_3d_mf.hdf5" #particles_3d_mf.hdf5 brightfield_particles.hdf5
  num_workers: 12
training:
  batch_size: 32 #16000
  num_epochs: 600
  device: "cuda:0"
  optimizer:
    type: "Adam"
    parameters:
      lr: 1e-4 #5e-2
      weight_decay: 5e-4 #5e-2
  scheduler:
    type: "ReduceLROnPlateau"
    parameters:
      mode: "min"
      factor: 0.5
      patience: 8
  early_stopping:
    enabled: true
    patience: 20
  loss:
    knn_divergence:
      weight: 0.8     # Weight for KNN divergence loss
    monotonicity:
      weight: 1     # Weight for monotonicity loss
  # Parameters for the target size distribution
  target_distribution:
    num_points: 30000 # Number of points in the target distribution
    mean: 76          # Mean of the target normal distribution (in nm) # for 300nm: 302, for 80nm: 76 
    std: 22.5         # Standard deviation of the distribution (in nm) # for 300nm: 25, for 80nm: 22.5
    min_value: 10.0   # Minimum size value (in nm)
    max_value: null   # Maximum size value (in nm), null means no maximum
    k: 3000           # k parameter for KNN divergence loss
    cycle: 5          # Regenerate distribution every N epochs
  classes: ${data.classes}  # Classes to include in training
logging:
  tensorboard:
    log_dir: "experiments/runs/size_prediction"
